### get
GET http://localhost:3000/work-items


### post
POST http://localhost:3000/work-items
Content-Type: application/json
Accept: application/json
Connection: keep-alive

{
  "text": "abc2"
}

### get users
GET http://localhost:3000/users

### post users
POST http://localhost:3000/users
Content-Type: application/json
Accept: application/json
Connection: keep-alive

{
  "firstName": "tester",
  "lastName": "fun",
  "age": 27
}


### Get Movies
GET http://localhost:3000/api/v1/movies


### Post Movies
POST http://localhost:3000/api/v1/movies
Content-Type: application/json
Accept: application/json
Connection: keep-alive

{
  "title": "test movie",
  "year": 2003
}
